### ISSUE TITLE
Artwork Folderpath?

### ISSUE THREAD

**Issue by NyxoLyno** [Silverwulf/PosterPy#1]
I've been trying to get this to work for hours.

Can you please explain to me what goes in the Art Folder Path in the config file?

Is it my Plex folder location on the server?  A separate folder on the Pi?  The cache folder on the server?

Without an thorough readme file, I'm left a little in the dark here.

Everything is working, except pulling the posters, and I suspect it's from not having the artwork file path set correctly.

**Comment by Silverwulf** [comment]
The art folder path is where you want to source the artwork from when nothing is playing on your Plex Server. I have mine running from a separate folder on the pi. You will need a file path that looks something like this: "/home/pi/PosterPi/Images/Artwork/" for it to work
